version: '3'
services:
  spark-working-env:
    image: jupyter/pyspark-notebook:python-3.8
    container_name: spark-working-env
    ports:
      - 8888:8888
    volumes:
      - ./data:/home/jovyan/data
      - ./batch:/home/jovyan/batch
      - ./structured_streaming:/home/jovyan/structured_streaming
    networks:
      - dataeng-data-platform

networks:
  dataeng-data-platform:
    external: true
      