version: '3'
services:
  spark-env:
    build: .
    container_name: spark-env
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ~/my-repos/datalake:/home/jovyan/data
      - ./batch:/home/jovyan/batch
      - ./structured_streaming:/home/jovyan/structured_streaming
      - ./deltalake:/home/jovyan/deltalake
    networks:
      - dataeng-data-platform

networks:
  dataeng-data-platform:
    external: true