version: '3'
services:
  spark-env:
    build: .
    container_name: spark-env
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./batch:/home/jovyan/batch
      - ./structured_streaming:/home/jovyan/structured_streaming
      - ./deltalake:/home/jovyan/deltalake
      - ./postgresql-42.2.20.jar:/home/jovyan/jars/postgresql-42.2.20.jar
      - ../challenges:/home/jovyan/challenges
      - ./spark-config/spark-defaults.conf:/usr/local/spark/conf/spark-defaults.conf
      - ./spark-config/hive-site.xml:/usr/local/spark/conf/hive-site.xml
    networks:
      - dataeng-data-platform

networks:
  dataeng-data-platform:
    external: true